name: rtdaq_ion
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pip
  - pyvisa
  - numpy
  - xarray
  - pyqtgraph
  - qtpy
  - matplotlib
  - ipykernel
  - ipywidgets
  - jupyter
  - pyside6
